import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import { ProviderLayout } from "@/provider";
import { BottomNavigation } from "@/components/module";

import "./globals.css";

const inter = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <ProviderLayout>
        <body className={`${inter.className} bg-gray-200`}>
          <div className="flex mx-auto bg-white max-w-[500px] h-[100vh] overflow-hidden overflow-y-scroll center-box">
            {children}
          </div>
          <div className="relative flex justify-center items-center bottom-9 ">
            <BottomNavigation />
          </div>
        </body>
      </ProviderLayout>
    </html>
  );
}
